docker-compose-yaml: docker-compose.yml
environments:
  real-ip-test:
    routes:
      - nginx:
        - "frontend-test.test6.shreddedbacon.com":
            pathRoutes:
              - toService: backend
                path: /api
              - toService: backend
                path: /cms

