server {

    listen 8080 default_server;

    include /etc/nginx/helpers/*.conf;

    location = /cms {
        proxy_pass http://backend:8080;
    }

    location = /api {
        proxy_pass http://backend:8080;
    }
}