services:
  nginx:
    build:
      context: frontend
      dockerfile: Dockerfile
    labels:
      lagoon.type: nginx
    ports:
      - "8080:8080"
  backend:
    build:
      context: backend-proxy
      dockerfile: backend.Dockerfile
    labels:
      lagoon.type: nginx
    ports:
      - "8081:8080"